# Generated by Django 3.1.7 on 2021-04-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('department_created_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.BooleanField(blank=True, default=True, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_app.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.BooleanField(blank=True, default=True, null=True)),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_app.doctors')),
            ],
        ),
    ]
