# Generated by Django 3.1.7 on 2021-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_auto_20210411_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
