# Generated by Django 3.1.7 on 2021-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_doctors_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
