# Generated by Django 3.0.4 on 2020-11-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mobile_no',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pan_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
