# Generated by Django 3.0.4 on 2020-11-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0002_auto_20201117_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='pan_no',
        ),
    ]
