# Generated by Django 3.1.7 on 2021-04-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_1', models.CharField(max_length=200, null=True)),
                ('option_2', models.CharField(max_length=200, null=True)),
                ('option_3', models.CharField(max_length=200, null=True)),
                ('option_4', models.CharField(max_length=200, null=True)),
                ('correct_option', models.CharField(max_length=200, null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.exam')),
            ],
        ),
    ]
